### ISSUE TITLE
Update NFT abi

### ISSUE THREAD

**Issue by jakeloo** [nftlabs/nftlabs-sdk-python#37]
we've updated NFT abi to support signature based minting.

- [x]  setup a separate module and update it to match the new abi.
- [x] provide a way to access old module and the new module. maybe, `get_nft_module("address", v1=True)` to access the old version, defaults to new one.
- [ ] update mint functions to match parity with the typescript sdk.

**Comment by ayshptk** [comment]
pausing this because we need multicall on python, would need help from @atbe for this

**Comment by atbe** [comment]
Merged and released in `v0.5.0`
