### ISSUE TITLE
pip install taking long time for Sundial

### ISSUE THREAD

**Issue by eabdelmoneim** [nftlabs/nftlabs-sdk-python#43]
From Sundial:

![Screen Shot 2022-01-20 at 1 27 33 PM](https://user-images.githubusercontent.com/10700302/150408532-6d09ef41-cf3a-49b6-a272-9c90f743b493.png)

**Comment by atbe** [comment]
Closing this as per @jakeloo request, item was resolved by customer without any changes on our side
